# Generated by Django 5.0.6 on 2024-06-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='problem',
            fields=[
                ('date', models.DateField(auto_created=True)),
                ('Problem_ID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('statement', models.TextField()),
                ('tags', models.CharField(max_length=50)),
            ],
        ),
    ]
