# Generated by Django 5.0.6 on 2024-06-25 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='statement',
            new_name='question',
        ),
    ]
