# Generated by Django 5.0.6 on 2024-06-26 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_rename_statement_problem_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_cases',
            fields=[
                ('Test_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Input', models.TextField()),
                ('output', models.TextField()),
                ('Problem_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem')),
            ],
        ),
    ]
