# Generated by Django 5.0.6 on 2024-07-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_alter_problem_date_alter_submission_time_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='test',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='easy', max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('cpp', 'c++'), ('py', 'python'), ('java', 'Java'), ('c', 'C')], default='c++', max_length=20),
        ),
    ]
