# Generated by Django 5.0.6 on 2024-07-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_submission_test_alter_problem_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='code',
            field=models.TextField(default=' '),
        ),
    ]
