# Generated by Django 5.0.6 on 2024-07-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0009_alter_submission_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='code',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='submission',
            name='test',
            field=models.TextField(default=''),
        ),
    ]
