# Generated by Django 5.0.6 on 2024-07-06 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0012_save_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='save_code',
            old_name='User_ID',
            new_name='User',
        ),
        migrations.RemoveField(
            model_name='save_code',
            name='solved',
        ),
    ]
