# Generated by Django 5.0.6 on 2024-07-10 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0017_rename_tags_tag_alter_problem_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='tags',
        ),
    ]
