# Generated by Django 5.0.6 on 2024-07-10 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0020_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tags',
        ),
    ]
