# Generated by Django 5.0.6 on 2024-07-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0021_delete_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_tags',
            field=models.ManyToManyField(blank=True, to='problems.tag'),
        ),
    ]
