# Generated by Django 5.0.6 on 2024-07-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0022_problem_problem_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='problem_tags',
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_tags',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
