# Generated by Django 5.0.6 on 2024-07-10 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0023_remove_problem_problem_tags_problem_problem_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
